### ISSUE TITLE
Negative electronic configuration in scf

### ISSUE THREAD

**Issue by LavendaRaphael** [times-software/feff10#12]
I am using feff10.0 to perform O K-edge XANES simulation on a Pt/O surface system.
But after the first SCF cycle, `convergence.scf.fine` gave me this non-physical negative electron configuration:
```
 SCF ITERATION NUMBER  1
   Electronic configuration
   type     l     N_el
      0     0    1.455
      0     1    3.711
      0     2   -3.679
      0     3    0.000
      1     0    1.455
...
```
And the stdout `feff.log` show:
```
...
 Found bad counts.
  Occupation number in getorb is     0.000
  Will repeat this iteration
 Found bad counts.
  Occupation number in getorb is     1.000
  Will repeat this iteration
 Found bad counts.
  Occupation number in getorb is     0.000
  Will repeat this iteration
 Found bad counts.
  Occupation number in getorb is     0.000
  Will repeat this iteration
 Found bad counts.
  Occupation number in getorb is     1.000
  Will repeat this iteration
 Found bad counts.
  Occupation number in getorb is     0.000
  Will repeat this iteration
 Found bad counts.
  Occupation number in getorb is     0.000
  Will repeat this iteration
 FRNRM Could not integrate enough charge to reach required z.
 FRNRM-1
...
```
All the related files have been attached. Is there any suggestions?
[test.zip](https://github.com/times-software/feff10/files/7689486/test.zip)

## feff.inp
```
CIF feff.cif
RECIPROCAL
TARGET 1
TITLE test
XANES 4.0
POLARIZATION 0.0 0.0 1.0
KMESH 100
EGRID
e_grid -10 20 0.1
COREHOLE RPA
EDGE K
SCF 7.0
* EXCHANGE 0 0 0.0
* CHBROADENING 0
CHWIDTH 0.45
FMS 9.0 0 2
* CORRECTIONS 0.0 0.0
ABSOLUTE
```

**Comment by jjkas** [comment]
Hi Feifei,
It seems the automatic choice of Ewald parameter eta. You can fix this by
including the STRFAC card:
STRFAC 1.0 0.0 0.0
Let me know if this works.

**Comment by LavendaRaphael** [comment]
> Hi Feifei, 
> It seems the automatic choice of Ewald parameter eta. You can fix this by including the STRFAC card: 
> STRFAC 1.0 0.0 0.0 
> Let me know if this works.

@jjkas Thank you very much. Your suggestion works well for me!
